### ISSUE TITLE
Provide resources for additional containers

### ISSUE THREAD

**Issue by AlissonRS** [juicedata/charts#123]
In the CSI chart, both the controller (StatefulSet) and node (DaemonSet) have additional controllers without proper resources defined.

It would be nice if some defaults were provided, OR if a field was available in the chart so we can configure it.

**Comment by zwwhdls** [comment]
It is configurable in values.yaml: https://github.com/juicedata/charts/blob/main/charts/juicefs-csi-driver/values.yaml#L208
