### ISSUE TITLE
Charts repository appears to be empty

### ISSUE THREAD

**Issue by av-mathiaspius** [juicedata/charts#32]
When attempting to install the juicefs-csi-driver using helm, the chart cannot be found.

Navigating to https://juicedata.github.io/charts/ also displays no charts.

**Comment by zwwhdls** [comment]
Please refer to https://juicefs.com/docs/csi/getting_started#install-via-helm.

**Comment by av-mathiaspius** [comment]
I apologize, I believe this issue might have been caused by https://www.githubstatus.com/incidents/ljwdk6qml8z8 which was when I tested it, and was getting errors fetching charts.
