### ISSUE TITLE
process mount mode does not work

### ISSUE THREAD

**Issue by jgillich** [juicedata/charts#42]
`POD_NAME` is not set when using process mount mode: https://github.com/juicedata/charts/blob/9a907807d321830cffaed448c3e906e9b7027e8c/charts/juicefs-csi-driver/templates/controller.yaml#L50

But csi-driver does nothing when `POD_NAME` is not set: https://github.com/juicedata/juicefs-csi-driver/blob/afb8cf3de13e8c76a3f3ee79d038eaf3e9f2960d/cmd/main.go#L78

**Comment by zwwhdls** [comment]
Hi @jgillich , what problem have you met?

**Comment by jgillich** [comment]
So as you pointed out, I probably don't want to be using process mode

But this issue is of a different nature, when the chart is deployed with `mountMode: process` (without provisioner or any other options), it generates CSI controller/node pods that do nothing whatsoever, they simply exit with status 0 right away. This is because the csi driver only does something if `POD_NAME` is set.
