### ISSUE TITLE
add support for imagePullSecrets

### ISSUE THREAD

**Issue by fungaren** [juicedata/charts#47]
As described in:
https://helm.sh/docs/howto/charts_tips_and_tricks/#creating-image-pull-secrets

BTW, is it necessary for CSI Controller to support `hostNetwork`? As I can see, it only support `hostNetwork` for CSI Node.

BTW, it is also supposed to support changing liveness probe port `HEALTH_PORT` in `values.yaml` (especially when you are using host network mode.

**Comment by fungaren** [comment]
BTW, currently the sidecars are fairly old (as your document said, to support ARM64 machines we must upgrade them MANUALLY). Why not upgrade them to the newer version and make the support for non-x86 machines out-of-box.

To ways to get the latest image tag:

- https://explore.ggcr.dev/
- Use `gcrane ls` command, described in https://github.com/google/go-containerregistry/blob/main/cmd/gcrane/README.md

**Comment by zwwhdls** [comment]
Hi @fungaren , sorry for delay reply. `imagePullSecrets` has been supported and the problem has been fixed too. Please upgrade chart and try again. Thanks!
